### ISSUE TITLE
WebDev16 edit wiki link broken

### ISSUE THREAD

**Issue by j4yk** [LivelyKernel/Lively4#12]
The [wiki page](https://github.com/LivelyKernel/Lively4/wiki/WebDev16) says "For we can for example navigate and edit these wiki pages using the [our server on lively-kernel.org](https://lively-kernel.org/lively4/draft/start.html?load=https://lively-kernel.org/lively4/Wiki/WebDev16.md)"  but that link leads me to a plain "File not found!" page.

Edit OT: but I confirm that being logged in is enough to edit the wiki on GitHub.

**Comment by JensLincke** [comment]
fixed... updated link to https://lively-kernel.org/lively4/lively4-core/draft/start.html?load=https://lively-kernel.org/lively4/Lively4.wiki/WebDev16.md
